version: "3.8"

services:
  backend:
    build: .
    restart: always
    image: apteryx/docker_traefik_tiangolo:v1
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`kikididi.io`)
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true